"""added message_type column

Revision ID: 01c1ce096392
Revises: 28c2ebfd7995
Create Date: 2026-04-21 17:32:16.534988
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '01c1ce096392'
down_revision = '28c2ebfd7995'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_type', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_messages_message_type'), 'messages', ['message_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_message_type'), table_name='messages')
    op.drop_column('messages', 'message_type')
    # ### end Alembic commands ###
