"""added relay_node column

Revision ID: 0f9a9bcb25eb
Revises: 01c1ce096392
Create Date: 2026-04-21 17:34:06.453079
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '0f9a9bcb25eb'
down_revision = '01c1ce096392'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('relay_node', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_messages_relay_node'), 'messages', ['relay_node'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_relay_node'), table_name='messages')
    op.drop_column('messages', 'relay_node')
    # ### end Alembic commands ###
