"""adding node table

Revision ID: 201a3e115b30
Revises: b15f2e0a8c31
Create Date: 2026-04-22 23:04:31.964988
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '201a3e115b30'
down_revision = 'b15f2e0a8c31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('backend_id', sa.String(length=128), nullable=False),
    sa.Column('last_byte', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['backend_id'], ['backend_instances.backend_id'], ),
    sa.PrimaryKeyConstraint('node_id', 'backend_id')
    )
    op.create_index(op.f('ix_nodes_backend_id'), 'nodes', ['backend_id'], unique=False)
    op.create_index(op.f('ix_nodes_node_id'), 'nodes', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodes_node_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_backend_id'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###
