"""added portnum column

Revision ID: 28c2ebfd7995
Revises: aa5ef7219046
Create Date: 2026-04-20 14:26:37.003355
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '28c2ebfd7995'
down_revision = 'aa5ef7219046'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('portnum', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_messages_portnum'), 'messages', ['portnum'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_portnum'), table_name='messages')
    op.drop_column('messages', 'portnum')
    # ### end Alembic commands ###
