"""hops_away column is added to messages column

Revision ID: 311d32c9e8c0
Revises: 201a3e115b30
Create Date: 2026-04-23 20:10:20.122252
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '311d32c9e8c0'
down_revision = '201a3e115b30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('hops_away', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'hops_away')
    # ### end Alembic commands ###
