"""added request_id column

Revision ID: 96d580b2024d
Revises: 0f9a9bcb25eb
Create Date: 2026-04-21 21:15:28.859681
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '96d580b2024d'
down_revision = '0f9a9bcb25eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('request_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_messages_request_id'), 'messages', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_request_id'), table_name='messages')
    op.drop_column('messages', 'request_id')
    # ### end Alembic commands ###
