"""added messages table

Revision ID: aa5ef7219046
Revises: 20260407_0002
Create Date: 2026-04-20 11:36:33.845767
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'aa5ef7219046'
down_revision = '20260407_0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('destination', sa.String(length=128), nullable=False),
    sa.Column('reporter', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sequence_number', sa.BigInteger(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('next_hop', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_destination'), 'messages', ['destination'], unique=False)
    op.create_index(op.f('ix_messages_next_hop'), 'messages', ['next_hop'], unique=False)
    op.create_index(op.f('ix_messages_reporter'), 'messages', ['reporter'], unique=False)
    op.create_index(op.f('ix_messages_source'), 'messages', ['source'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.drop_column('mqtt_messages', 'payload_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mqtt_messages', sa.Column('payload_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index(op.f('ix_messages_source'), table_name='messages')
    op.drop_index(op.f('ix_messages_reporter'), table_name='messages')
    op.drop_index(op.f('ix_messages_next_hop'), table_name='messages')
    op.drop_index(op.f('ix_messages_destination'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
